apiVersion: v1
kind: ConfigMap
metadata:
  name: light-ratelimit-config
  namespace: istio-system
data:
  light-ratelimit-config.yaml: |
    domain: api
    descriptors:
      - key: path
        value: /light*
        rate_limit:
          unit: minute
          requests_per_unit: 3
